apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodepoolallocationtargets.jupyter.org
spec:
  scope: Cluster
  group: jupyter.org
  names:
    kind: NodepoolAllocationTarget
    plural: nodepoolallocationtargets
    singular: nodepoolallocationtarget
    shortNames:
      - npats
      - npat
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      - name: Node count
        type: integer
        description: Current node count
        jsonPath: .status.create_npat.node_count
      - name: Min node count
        type: integer
        description: Minimum node count
        jsonPath: .status.create_npat.min_node_count
      - name: Max node count
        type: integer
        description: Maximum node count
        jsonPath: .status.create_npat.max_node_count
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp